# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 00:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=datetime.datetime(2018, 4, 1, 0, 0, 28, 158682))),
                ('client_id', models.CharField(max_length=256)),
                ('auth_token', models.CharField(default=b'f48aca16-0a7d-4e84-a7c4-651c78f43a36', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('email', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('dob', models.DateTimeField(null=True)),
                ('password', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[(b'MALE', b'MALE'), (b'FEMALE', b'FEMALE'), (b'OTHER', b'OTHER')], default=None, max_length=124)),
                ('profile_pic', models.CharField(max_length=512)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 4, 1, 0, 0, 28, 157808))),
            ],
        ),
        migrations.AddField(
            model_name='loginentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_models.User'),
        ),
    ]
