# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-28 13:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0003_auto_20180421_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginentry',
            name='auth_token',
            field=models.CharField(default=b'c30d0684-5ffa-4b69-97a2-1f711c18fbb2', max_length=512),
        ),
        migrations.AlterField(
            model_name='loginentry',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 28, 13, 27, 11, 428877)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 28, 13, 27, 11, 428275)),
        ),
    ]
