# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 10:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0004_auto_20180428_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginentry',
            name='auth_token',
            field=models.CharField(default=b'af89e5a2-d5be-4ac9-91d1-f84d83e0c15d', max_length=512),
        ),
        migrations.AlterField(
            model_name='loginentry',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 1, 10, 17, 0, 128556)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 1, 10, 17, 0, 127449)),
        ),
    ]
