# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-28 13:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_models', '0005_auto_20180428_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 28, 13, 16, 7, 259604)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 28, 13, 16, 7, 259023)),
        ),
    ]
