# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-29 00:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_models', '0008_auto_20180428_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 0, 15, 29, 993862)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 0, 15, 29, 992621)),
        ),
    ]
