# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 10:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_models', '0009_auto_20180429_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 1, 10, 21, 29, 526396)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 1, 10, 21, 29, 525767)),
        ),
    ]
