# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 20:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_models', '0010_auto_20180501_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 1, 20, 41, 20, 787625)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 1, 20, 41, 20, 784573)),
        ),
    ]
